apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://wlgns1210.github.io/test-repo/charts
    chart: app
    targetRevision: 0.1.0
    helm:
      valueFiles:
        - dev.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: product
  syncPolicy: {}
