image:
repository: ""
tag: ""
pullPolicy: IfNotPresent


replicaCount: 2


service:
port: 80
targetPort: 8080


rollout:
name: product
namespace: product
strategy:
autoPromotionEnabled: true
autoPromotionSeconds: 0
scaleDownDelaySeconds: 0