name: Dev Auto Merge & Deploy

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  id-token: write
  actions: read

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: product/dev
  DOCKERFILE_PATH: ./Dockerfile
  VALUES_FILE: values/dev.values.yaml
  ARGOCD_TIMEOUT: 180   # wait timeout 연장

jobs:
  auto-merge-and-deploy:
    runs-on: [self-hosted, dev]
    timeout-minutes: 10
    steps:
      # 1️⃣ PR 브랜치 Checkout
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ feature/* 브랜치 검증
      - name: Verify feature branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" != feature/* ]]; then
            echo "Not a feature branch PR. Skipping job."
            exit 0
          fi

      # 3️⃣ Git config
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 4️⃣ PR 자동 Merge
      - name: Auto merge PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto --delete-branch

      # 5️⃣ Merge 후 dev 브랜치 Checkout
      - name: Checkout dev branch after merge
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # 7️⃣ AWS Credentials 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          role-session-name: GitHubActions-Dev
          aws-region: ${{ env.AWS_REGION }}

      # 8️⃣ ECR Login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 9️⃣ Commit SHA 가져오기
      - name: Get commit SHA
        id: commit
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # 🔟 Docker Build & Push (if ARM flag 필요 시 분기)
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.commit.outputs.sha }}
        run: |
          # 기본은 amd64
          PLATFORMS="linux/amd64"
          if [[ "${{ github.event.pull_request.head.ref }}" == *-arm ]]; then
            PLATFORMS="linux/amd64,linux/arm64"
          fi

          docker buildx build \
            --platform $PLATFORMS \
            --file $DOCKERFILE_PATH \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --push \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .

      # 11️⃣ dev values.yaml 이미지 태그 업데이트
      - name: Update values file
        env:
          IMAGE_TAG: ${{ steps.commit.outputs.sha }}
        run: |
          # image.tag만 변경
          sed -i "s|^\(\s*tag:\s*\).*|\1$IMAGE_TAG|" $VALUES_FILE
          git add $VALUES_FILE
          git commit -m "chore: update dev image tag to $IMAGE_TAG [skip ci]" || exit 0
          git push origin dev

      # 12️⃣ ArgoCD 수동 Sync
      - name: Trigger ArgoCD Sync
        run: |
          /tmp/argocd app sync $APP_NAME \
            --server $ARGOCD_SERVER \
            --auth-token $ARGOCD_TOKEN \
            --insecure \
            --force
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN_DEV }}
          APP_NAME: ${{ secrets.ARGOCD_APP_NAME_DEV }}

      - name: Wait for deployment
        run: |
          /tmp/argocd app wait $APP_NAME \
            --server $ARGOCD_SERVER \
            --auth-token $ARGOCD_TOKEN \
            --insecure \
            --timeout 180 || echo "Deployment wait timed out but continuing"
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN_DEV }}
          APP_NAME: ${{ secrets.ARGOCD_APP_NAME_DEV }}


      # 14️⃣ PR Comment
      - name: Comment on PR
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            gh pr comment ${{ github.event.number }} --body "✅ Dev deployment successful! Image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.commit.outputs.sha }} Deployed to dev cluster via ArgoCD."
          else
            gh pr comment ${{ github.event.number }} --body "❌ Dev deployment failed. Please check the workflow logs."
          fi
