
name: Dev Pipeline

on:
  pull_request:
    branches: [ "dev" ]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  merge-build-deploy:
    runs-on: [self-hosted, linux, dev]
    timeout-minutes: 5
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure PR is from feature/*
        if: ${{ !startsWith(github.head_ref, 'feature/') }}
        run: |
          echo "This workflow only auto-merges feature/* PRs" >&2
          exit 1

      - name: Merge PR into dev
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch --admin || \
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch

      - name: Get latest commit SHA
        id: sha
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password \
            | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/product/dev:${{ steps.sha.outputs.sha }}
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/product/dev:latest
          cache-from: type=registry,ref=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/product/dev:cache
          cache-to: type=registry,ref=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/product/dev:cache,mode=max

      - name: Update dev.values.yaml with new image tag
        run: |
          sed -i -E "s/tag: \".*\"/tag: \"${{ steps.sha.outputs.sha }}\"/" values/dev.values.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add values/dev.values.yaml
          git commit -m "chore(dev): update image tag ${{ steps.sha.outputs.sha }}" || echo "No changes"
          git push origin dev

      - name: ArgoCD Sync (dev)
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd --grpc-web login $ARGOCD_SERVER --insecure --auth-token $ARGOCD_AUTH_TOKEN
          argocd app sync dev --prune
          argocd app wait dev --health --timeout 60
