name: Dev Auto Merge & Deploy

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize]

jobs:
  dev-deploy:
    runs-on: [self-hosted, dev]  # dev-cluster runner 사용
    if: startsWith(github.event.pull_request.head.ref, 'feature/')
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auth GH CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token 

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<GITHUB_ACTIONS_ROLE>
          aws-region: ap-northeast-2

      - name: Fast-forward merge PR into dev
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --merge --admin --delete-branch

      - name: Checkout dev branch after merge
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 \
          | docker login --username AWS --password-stdin <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build & Push Docker Image (product/dev)
        run: |
          IMAGE_URI=<ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/product/dev:latest
          docker build -t $IMAGE_URI . --quiet
          docker push $IMAGE_URI

      - name: ArgoCD Sync (product-dev)
        run: |
          argocd app sync product-dev \
            --grpc-web \
            --server $ARGOCD_SERVER \
            --auth-token $ARGOCD_AUTH_TOKEN \
            --timeout 60
